import type { Product, ReviewsSummary } from './types';

export const product: Product = {
  id: 'prod_head_massager_1',
  title: 'Electric Head & Body Massager (Rechargeable)',
  brand: 'Khushiyan',
  price: 999,
  compareAtPrice: 1899,
  images: [
    '/products/head-massager/1.jpg',
    '/products/head-massager/2.jpg',
    '/products/head-massager/3.jpg',
    '/products/head-massager/4.jpg'
  ],
  youtubeUrl: 'https://www.youtube.com/watch?v=RAKbZazdgqk',
  bullets: [
    'Instant relaxation for head, neck and shoulders',
    'Improves blood circulation — relieves stress and headaches',
    'Deep scalp massage helps reduce hair fall and promotes growth',
    'Soft, flexible massage nodes — comfortable for all hair types',
    'Use on face, scalp, back and legs — full body relaxation',
    'Rechargeable and cordless — use anywhere, anytime'
  ],
  descriptionHeading: 'Spa-like relaxation at home',
  descriptionPoints: [
    '3D kneading action targets pressure points',
    'Daily 10 minutes helps improve sleep quality',
    'Lightweight and ergonomic design for easy grip',
  ],
  sku: 'HEAD-MASSAGER-RECHARGEABLE',
  inventoryStatus: 'IN_STOCK'
};

// Second product: Posture Corrector
export const postureCorrector: Product = {
  id: 'prod_posture_corrector_1',
  title: 'Posture Corrector Back Brace',
  brand: 'Khushiyan',
  price: 699,
  compareAtPrice: 1499,
  images: [
    '/products/posture-corrector/p1.jpg',
    '/products/posture-corrector/p2.jpg',
    '/products/posture-corrector/p3.jpg',
    '/products/posture-corrector/p4.jpg'
  ],
  // YouTube video will appear as 2nd item in gallery
  youtubeUrl: 'https://www.youtube.com/watch?v=cmQNrqAhhk8&t=1s',
  bullets: [
    'Instant posture support — shoulders back, spine aligned.',
    'Reduces back & neck pain during long sitting.',
    'Breathable, lightweight mesh — comfy all day.',
    'Adjustable straps — secure unisex fit.',
    'Trains muscles for naturally better posture.',
    'Slim design — discreet under t‑shirts and shirts.',
  ],
  descriptionHeading: 'Stand tall. Sit right.',
  descriptionPoints: [
    'Daily 20–30 minutes helps build muscle memory',
    'Improves posture and reduces fatigue while working',
    'Easy to wear, no tools needed',
    'Helps prevent slouching during work or study',
    'Soft edges — no underarm chafing',
    'Unisex fit with adjustable straps for teens and adults'
  ],
  sku: 'POSTURE-CORRECTOR',
  inventoryStatus: 'IN_STOCK'
};

// Third product: Electric Foot Massager Mat
export const footMassager: Product = {
  id: 'prod_foot_massager_mat_1',
  title: 'Electric Foot Massager Mat',
  brand: 'Khushiyan',
  price: 699,
  compareAtPrice: 1799,
  images: [
    '/products/foot-massager/fm1.jpg',
    '/products/foot-massager/fm2.jpg',
    '/products/foot-massager/fm3.jpg',
    '/products/foot-massager/fm4.jpg',
  ],
  // YouTube video appears as 2nd item in gallery
  youtubeUrl: 'https://www.youtube.com/watch?v=muh4awUNlJg&t=1s',
  bullets: [
    'EMS technology gently stimulates tired feet',
    'Relieves soreness after long standing or walking',
    'Foldable mat — ultra thin and portable',
    'Multiple intensity levels — from gentle to strong',
    'Use barefoot — easy wipe-clean surface',
    'USB rechargeable — long battery life',
  ],
  descriptionHeading: 'Soothe sore feet in minutes',
  descriptionPoints: [
    'Targets acupressure points with EMS pulses',
    'Great for plantar fatigue and swollen feet',
    '6 modes × 10 intensity levels for a custom massage',
    'Lightweight foldable mat fits in your bag',
    'Skin‑friendly PU surface — easy to clean',
    'USB Type‑C charging; use anywhere, anytime',
    'Auto shut‑off for safe home use',
    'Quiet operation — relax while watching TV'
  ],
  sku: 'FOOT-MASSAGER-MAT',
  inventoryStatus: 'IN_STOCK'
};

// Fourth product: Electric Gel Bottle Pouch Massager (Heating Pad)
export const electricHeatingPad: Product = {
  id: 'prod_electric_heating_pad_1',
  title: 'Electric Gel Bottle Pouch Massager',
  brand: 'Khushiyan',
  price: 359,
  compareAtPrice: 1299,
  images: [
    '/products/electric-heating-pad/hp1.jpg',
    '/products/electric-heating-pad/hp3.jpg',
    '/products/electric-heating-pad/hp4.jpg',
    '/products/electric-heating-pad/hp5.jpg',
  ],
  // YouTube video will appear as 2nd item in gallery
  youtubeUrl: 'https://www.youtube.com/watch?v=3ZSCr3N4Pds',
  bullets: [
    'Quick heat therapy for back, neck, shoulder, and cramps',
    'Soft gel pouch retains heat longer for deeper relief',
    'Dual heating levels with auto cut‑off safety',
    'Reusable — just plug in, heat, and enjoy warm comfort',
    'Comfortable fabric cover; gentle on skin',
    'Portable and lightweight — perfect for home or office',
  ],
  descriptionHeading: 'Instant warm comfort. Anywhere.',
  descriptionPoints: [
    'Targets everyday aches — muscle strain, period cramps, and stiffness',
    'Fast heating element warms gel evenly in minutes',
    'Leak‑proof build with reinforced sealing for safety',
    'Ergonomic pouch shape fits back and abdomen comfortably',
    'Energy‑efficient with auto shut‑off to prevent overheating',
    'Easy maintenance — wipe clean after use',
  ],
  sku: 'ELECTRIC-HEATING-PAD',
  inventoryStatus: 'IN_STOCK',
};

// Fifth product: Mimo Mini Vibration Full Body Massager
export const mimoMiniMassager: Product = {
  id: 'prod_mimo_mini_massager_1',
  title: 'Mimo Mini Vibration Full Body Massager',
  brand: 'Khushiyan',
  price: 599,
  compareAtPrice: 999,
  images: [
    '/products/mimi-mini-body-massager/mb1.jpg',
    '/products/mimi-mini-body-massager/mb2.jpg',
    '/products/mimi-mini-body-massager/mb3.jpg',
    '/products/mimi-mini-body-massager/mb4.jpg',
  ],
  youtubeUrl: 'https://www.youtube.com/watch?v=2_jfuBmbzqk&t=1s',
  bullets: [
    'Compact 3‑point design — head, neck, shoulder, back & legs',
    'Deep vibration helps relax stiff muscles and reduces fatigue',
    'One‑button operation — easy for all ages',
    'USB powered — use with power bank, laptop or adapter',
    'Lightweight and portable — carry to office or travel',
    'Low noise motor for a calm, soothing experience',
  ],
  descriptionHeading: 'Anytime refresh. Pocket‑size relief.',
  descriptionPoints: [
    'Targets pressure points with powerful micro‑vibrations',
    'Ergonomic shape fits naturally in the palm for better control',
    'Use on neck, shoulders, back, arms and calves after long hours',
    'Durable ABS body with soft‑touch legs for stable grip',
    'Perfect quick massage while studying, gaming or office breaks',
  ],
  sku: 'MIMO-MINI-MASSAGER',
  inventoryStatus: 'IN_STOCK',
};

// Sixth product: Mini Butterfly Massager
export const miniButterflyMassager: Product = {
  id: 'prod_mini_butterfly_massager_1',
  title: 'Mini Butterfly Massager',
  brand: 'Khushiyan',
  price: 549,
  compareAtPrice: 999,
  images: [
    '/products/mini-butterfly-massager/bm1.jpg',
    '/products/mini-butterfly-massager/bm2.jpg',
    '/products/mini-butterfly-massager/bm3.jpg',
    '/products/mini-butterfly-massager/bm4.jpg',
  ],
  youtubeUrl: 'https://www.youtube.com/watch?v=5i5N5qyXqrY&t=3s',
  bullets: [
    'Compact butterfly pad — target neck, shoulder, back & arms',
    'Soothing micro‑pulses help relax tight muscles',
    'Multiple modes with adjustable intensity levels',
    'Reusable gel pads — soft on skin and easy to replace',
    'USB rechargeable — carry to gym, office or travel',
    'One‑button operation — quick relief anytime',
  ],
  descriptionHeading: 'Stick. Relax. Refresh.',
  descriptionPoints: [
    'Ultra‑thin, flexible design fits comfortably on body curves',
    'Use after workouts or long desk hours to reduce stiffness',
    'Modes designed for warm‑up, relaxation and recovery',
    'Low noise operation — calm, discreet sessions',
    'Portable case friendly — take it anywhere',
  ],
  sku: 'MINI-BUTTERFLY-MASSAGER',
  inventoryStatus: 'IN_STOCK',
};

// Seventh product: Kitchen Weighing Scale
export const kitchenWeighingScale: Product = {
  id: 'prod_kitchen_weighing_scale_1',
  title: 'Kitchen Weighing Scale',
  brand: 'Khushiyan',
  price: 2,
  compareAtPrice: 1199,
  images: [
    '/products/kitchen-weighing-scale/ws1.jpg',
    '/products/kitchen-weighing-scale/ws2.jpg',
    '/products/kitchen-weighing-scale/ws3.jpg',
    '/products/kitchen-weighing-scale/ws4.jpg',
  ],
  youtubeUrl: 'https://www.youtube.com/watch?v=C5tzkjkVTaQ&t=2s',
  bullets: [
    'Accurate 1 g precision — ideal for baking & meal prep',
    'Up to 10 kg capacity with stable platform',
    'Tare function — zero the bowl for net weight',
    'Clear LCD display with easy buttons',
    'Auto shut‑off, low‑battery and overload indicators',
    'Slim, lightweight design — easy to store',
  ],
  descriptionHeading: 'Measure smart. Cook better.',
  descriptionPoints: [
    'Switch units: g, kg, oz, lb as per recipe',
    'Non‑slip feet keep the scale steady on countertops',
    'Energy efficient — long battery life',
    'Food‑safe easy‑clean surface',
    'Perfect for portion control and diet tracking',
  ],
  sku: 'KITCHEN-WEIGHING-SCALE',
  inventoryStatus: 'IN_STOCK',
};






// Map products by slug used in routes (/p/:slug)
export const productsBySlug: Record<string, Product> = {
  'head-massager': product,
  'posture-corrector': postureCorrector,
  'foot-massager': footMassager,
  'electric-heating-pad': electricHeatingPad,
  'mimo-mini-massager': mimoMiniMassager,
  'mini-butterfly-massager': miniButterflyMassager,
  'kitchen-weighing-scale': kitchenWeighingScale,
};


// Reviews: Foot Massager
export const reviewsFoot: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Rajeev P.', quote: 'Night shift ke baad pair bahut dukhte the — 15 min is mat pe and relief mil jata hai.', rating: 5 },
    { author: 'Megha T.', quote: 'Foldable aur lightweight. TV dekhte hue daily use karti hoon.', rating: 5 },
    { author: 'Suresh V.', quote: 'Walking ke baad thakawat utar jati hai. Pulses ka intensity adjustable hai.', rating: 4 },
    { author: 'Alka S.', quote: 'Swelling me kaafi help kiya. Mom ke liye bhi ek aur lene wali hoon.', rating: 5 },
    { author: 'Anurag K.', quote: 'Charging ek baar ki to 4–5 session chal jata hai. Worth the price.', rating: 4 },
    { author: 'Kavita D.', quote: 'Standing job me shaam ko pair soojh jate the — 10 min me halka feel hota hai.', rating: 5 },
    { author: 'Imran S.', quote: 'Mode 3, intensity 6 par best lagta hai. Easy controls.', rating: 4 },
    { author: 'Rupesh M.', quote: 'Gym leg day ke baad recovery fast lagti hai.', rating: 5 },
    { author: 'Sandhya L.', quote: 'Skin-friendly surface, wipe karna aasaan. Daily use.', rating: 5 },
    { author: 'Gagan B.', quote: 'Portable hai, travel bag me fold karke le jata hoon.', rating: 4 },
    { author: 'Prakash J.', quote: 'Papa ke liye liya tha, unko circulation me comfort milta hai.', rating: 5 },
    { author: 'Aanya R.', quote: 'Noise bilkul kam, TV dekhte hue use kar leti hoon.', rating: 5 },
    { author: 'Tarun P.', quote: 'Battery backup achha — 1 charge me 4 sessions ho gaye.', rating: 4 },
    { author: 'Zoya N.', quote: 'Design slim, floor pe slip nahi hota.', rating: 4 },
    { author: 'Bhavesh K.', quote: 'Pulses gentle se strong tak — sabko suit ho jayega.', rating: 5 },
    { author: 'Harleen C.', quote: 'Delivery fast aur product quality solid.', rating: 4 },
    { author: 'Nitin A.', quote: 'Morning walk ke baad sole pain kam ho jata hai.', rating: 5 },
    { author: 'Preeti V.', quote: 'Maa ke liye best gift, roz 15 min karti hain.', rating: 5 },
    { author: 'Farhan Q.', quote: 'USB Type-C se charge easy, wires ki tension nahi.', rating: 4 },
    { author: 'Mahima S.', quote: 'Surface soft lagta hai, koi irritation nahi.', rating: 5 },
    { author: 'Rajat T.', quote: 'Auto shut-off helpful, sone se pehle use kar leta hoon.', rating: 5 },
    { author: 'Sakshi P.', quote: 'Lightweight aur fold ho jata — cupboard me easily store.', rating: 5 },
    { author: 'Yogesh W.', quote: 'Office me lambi standing duty ke baad relief milta hai.', rating: 4 },
    { author: 'Nandini H.', quote: 'Modes ka variation badiya, relax aur recovery dono.', rating: 5 },
    { author: 'Altaf M.', quote: 'Value for money. Friends ko bhi recommend kiya.', rating: 5 },
    { author: 'Shubham D.', quote: 'Feet ke tingling me comfort mila, intensity 4 pe chalega.', rating: 4 },
    { author: 'Divya K.', quote: 'Setup simple — bas plug karo aur start.', rating: 5 },
    { author: 'Vikram R.', quote: 'Mat fold hota hai, backpack me easily aa jata.', rating: 4 },
    { author: 'Seema J.', quote: 'Sore ankles me bhi halka garam feel aur relax.', rating: 5 },
    { author: 'Kiran L.', quote: 'Cleaning easy — wet wipe se saaf ho gaya.', rating: 5 },
    { author: 'Arpita M.', quote: 'Varicose heaviness me halkapan feel hota hai. 2 weeks me farq.', rating: 4 },
    { author: 'Kunal J.', quote: 'Remote simple lagta hai, Mode 2 relax ke liye best.', rating: 5 },
    { author: 'Monika S.', quote: 'Elderly friendly — mummy ko kaafi pasand aaya.', rating: 5 },
    { author: 'Ramesh P.', quote: 'Office desk ke niche quietly use kar leta hoon.', rating: 4 },
    { author: 'Heena G.', quote: 'Socks utar ke use karo — contact better aur feel soothing.', rating: 5 },
    { author: 'Ajay N.', quote: 'Timer feature accha — overuse ka tension nahi.', rating: 4 },
    { author: 'Smita V.', quote: 'Foot arch pain me kaafi comfort mila.', rating: 5 },
    { author: 'Aftab I.', quote: 'Charging fast hai, build quality theek hai.', rating: 4 },
    { author: 'Pawan K.', quote: 'Travel me fold karke le jana easy.', rating: 5 },
    { author: 'Isha B.', quote: 'Intensity 3 par soothing, chubhan nahi hoti.', rating: 5 },
    { author: 'Saurabh D.', quote: 'Mat ki grip achhi — floor pe slip nahi hota.', rating: 4 },
    { author: 'Riddhi S.', quote: 'Gift diya family ko — sab ko pasand aaya.', rating: 5 },
    { author: 'Jeet R.', quote: 'Manual clear tha — 2 minute me samajh aa gaya.', rating: 5 },
    { author: 'Neelam T.', quote: 'Ek hafte me swelling kam mehsoos hui.', rating: 4 },
    { author: 'Parth S.', quote: 'WFH breaks me 10 min — refresh feel.', rating: 5 },
    { author: 'Rohan L.', quote: 'Recharge 2 din me ek baar kaafi rehta hai.', rating: 4 },
    { author: 'Tanya K.', quote: 'Minimal design, table ke side easily store.', rating: 5 },
    { author: 'Abhishek M.', quote: 'EMS pehli baar try kiya — unexpectedly pleasant.', rating: 5 },
    { author: 'Kirti P.', quote: 'Soles me garam-garam pulses — mast relaxation.', rating: 4 },
    { author: 'Devika J.', quote: 'Value for money — definitely recommend.', rating: 5 }
  ]
};

// Reviews: Mimo Mini Massager
export const reviewsMimo: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Vishal R.', quote: 'Chota sa device par vibration powerful hai. Office desk pe daily use karta hoon.', rating: 5 },
    { author: 'Ananya P.', quote: 'Neck aur shoulder stiffness ke liye quick relief. USB se chal jata hai—very handy!', rating: 5 },
    { author: 'Deep', quote: 'Travel friendly. Noise kam hai, TV dekhte hue use kar sakte ho.', rating: 4 },
    { author: 'Meera K.', quote: 'Palm me achha grip, teen legs pressure points pe sahi lagte hain.', rating: 4 },
    { author: 'Kartik', quote: 'Gift kiya tha, sabko pasand aaya. Price ke hisab se badiya performance.', rating: 5 },
    { author: 'Riya S.', quote: 'Study breaks me 5 min use karti hoon — head aur neck relax.', rating: 5 },
    { author: 'Harshit P.', quote: 'USB power bank se bhi chal gaya. Portable and handy.', rating: 4 },
    { author: 'Sneha G.', quote: 'Palm fit design, fingers thakte nahi. Daily routine ban gaya.', rating: 5 },
    { author: 'Karan V.', quote: 'Gaming ke baad wrist aur forearm ka tension nikal jata hai.', rating: 4 },
    { author: 'Pooja L.', quote: 'Mom ko knees me bhi mild massage ke liye use karwa diya — kaafi relief.', rating: 5 },
    { author: 'Zubair H.', quote: 'Noise low, call pe bhi use kar sakte ho. Good for office.', rating: 5 },
    { author: 'Ira T.', quote: 'Build quality solid, grip rubberized lagti hai.', rating: 4 },
    { author: 'Dhruv N.', quote: 'One button control — simple and effective.', rating: 5 },
    { author: 'Mahesh K.', quote: 'Battery backup decent, 3-4 sessions easily.', rating: 4 },
    { author: 'Tanya M.', quote: 'Gifted to dad, neck stiffness me kaafi aaram.', rating: 5 },
    { author: 'Gaurav B.', quote: 'Compact size — travel pouch me easily aa jata hai.', rating: 5 },
    { author: 'Roshni P.', quote: 'Head massage se headache kam feel hota hai.', rating: 4 },
    { author: 'Ankit S.', quote: 'Price ke hisab se value — daily use ke liye sahi.', rating: 5 },
    { author: 'Payal D.', quote: 'Teen legs ke points sahi jagah hit karte hain.', rating: 4 },
    { author: 'Raghav J.', quote: 'WFH me shoulders tight ho jate the — ab relax feel hota hai.', rating: 5 },
    { author: 'Ishita K.', quote: 'Charging fast, USB se plug-and-play.', rating: 4 },
    { author: 'Sandeep R.', quote: 'Motor powerful par gentle — ache points me relief.', rating: 5 },
    { author: 'Mehul C.', quote: 'Gaming breaks me quick refresh. Good buy.', rating: 5 },
    { author: 'Palak S.', quote: 'Compact aur sturdy — gir bhi gaya toh kuch nahi hua.', rating: 4 },
    { author: 'Vivek T.', quote: 'Back aur calves pe bhi kaam karta hai — multipurpose.', rating: 5 },
    { author: 'Kritika V.', quote: 'Design cute aur functional. Friends ne bhi poocha.', rating: 5 },
    { author: 'Yash A.', quote: 'Office commute me bhi carry — lightweight hai.', rating: 4 },
    { author: 'Monu P.', quote: 'One-click se mode change easy hota hai.', rating: 4 },
    { author: 'Aisha Z.', quote: 'Night study ke baad temples pe relax milta hai.', rating: 5 },
    { author: 'Kabir U.', quote: 'USB cord ka length theek, laptop se hi chala leta hoon.', rating: 4 },
    { author: 'Simran G.', quote: 'Stop-start responsive — koi lag nahi.', rating: 5 },
    { author: 'Ritika N.', quote: 'Palm pe vibration soothing — stress kam hota hai.', rating: 5 },
    { author: 'Aman J.', quote: 'Easy to clean, wipe se saaf ho jata.', rating: 4 },
    { author: 'Divyansh R.', quote: 'Daily 10 min neck area — stiffness gayab.', rating: 5 },
    { author: 'Himani D.', quote: 'Noise low — TV dekhte hue bhi distub nahi karta.', rating: 5 },
    { author: 'Tarun K.', quote: 'Ergonomic shape palm me perfect baithta hai.', rating: 4 },
    { author: 'Jenny S.', quote: 'Travel case me rakh liya. Perfect for flights.', rating: 5 },
    { author: 'Nikhil O.', quote: 'Value purchase — gifting ke liye bhi best.', rating: 5 },
    { author: 'Aarav M.', quote: 'Shoulder ke trigger points pe kaam karta hai.', rating: 4 },
    { author: 'Esha L.', quote: 'Teen legs soft-touch — skin pe comfortable.', rating: 5 },
    { author: 'Prachi K.', quote: 'Long meetings ke baad Sir dard me relief.', rating: 5 },
    { author: 'Utkarsh S.', quote: 'Charging indicator helpful hai.', rating: 4 },
    { author: 'Rehan I.', quote: 'Backpack pocket me fit, on-the-go.', rating: 5 },
    { author: 'Natasha P.', quote: 'Maa ko diya — unhe bhi pasand aa gaya.', rating: 5 },
    { author: 'Ojas V.', quote: 'Buttons tactile, feel good.', rating: 4 },
    { author: 'Tanvi R.', quote: 'Stressful day ke baad quick unwind.', rating: 5 },
    { author: 'Yuvraj K.', quote: 'Price aur performance balanced.', rating: 4 },
    { author: 'Anushka D.', quote: 'Compact + powerful — daily essential.', rating: 5 },
    { author: 'Dev P.', quote: 'Warranty info clear tha, delivery fast.', rating: 4 },
    { author: 'Naina Q.', quote: 'Bright color cute lagta hai. Good vibes!', rating: 5 }
  ]
};


// Reviews: Head Massager
export const reviewsHead: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Aman K.', quote: 'Within 2 weeks hair fall kam ho gaya. Scalp fresh aur nourished lagta hai.', rating: 5 },
    { author: 'Ritika S.', quote: 'Dandruff almost gayab! Baal zyada soft aur shiny ho gaye.', rating: 5 },
    { author: 'Neha P.', quote: 'Raat ko lagao, subah wash karo — growth me naya baby hair dikh raha hai. Totally worth it!', rating: 5 },
    { author: 'Vineet K.', quote: 'Value for money! Use karne me bahut comfortable aur daily relaxation milta hai.', rating: 4 },
    { author: 'Shreya G.', quote: 'Mom ke liye liya tha, migraine me kaafi relief milta hai. Build quality bhi acchi hai.', rating: 5 },
    { author: 'Ishaan V.', quote: 'Scalp massage se blood flow better feel hota hai, headache kam.', rating: 5 },
    { author: 'Aarti D.', quote: 'Shampoo se pehle 5 min — dandruff flakes noticeably kam.', rating: 4 },
    { author: 'Pawan S.', quote: 'Grip comfortable — hair pull nahi hota, smooth nodes.', rating: 5 },
    { author: 'Zara M.', quote: 'Daily raat me use, neend better aati hai.', rating: 5 },
    { author: 'Keshav R.', quote: 'Oil lagane ke baad use karo — absorption fast lagta hai.', rating: 4 },
    { author: 'Mansi L.', quote: 'Forehead tension aur sinus pressure me bhi relief.', rating: 5 },
    { author: 'Rohini P.', quote: 'Hair fall noticeably reduce hua 10 din me.', rating: 5 },
    { author: 'Aryan K.', quote: 'USB rechargeable — cord ki jhanjhat nahi.', rating: 4 },
    { author: 'Prerna J.', quote: 'Node soft hain — scalp pe sahi pressure dalte.', rating: 5 },
    { author: 'Sahil T.', quote: 'Gym ke baad neck stiffness ke liye best.', rating: 4 },
    { author: 'Megha B.', quote: 'Travel friendly, handbag me easily aa jata.', rating: 5 },
    { author: 'Farida S.', quote: 'Migraines me soothing lagta hai — short sessions kaafi.', rating: 5 },
    { author: 'Ayan D.', quote: 'Build quality premium, buttons tactile.', rating: 4 },
    { author: 'Kritika S.', quote: 'Hair wash se pehle 3-4 min — scalp squeaky clean lagta.', rating: 5 },
    { author: 'Dev R.', quote: 'Back aur calves pe bhi try kiya — achha feel.', rating: 4 },
    { author: 'Nidhi G.', quote: 'Charging ek hafta kaam chal jata light use me.', rating: 5 },
    { author: 'Harshita V.', quote: 'Daily 10 min — stress bahut kam ho jata hai.', rating: 5 },
    { author: 'Raman S.', quote: 'Design ergonomic, haath me ache se fit.', rating: 4 },
    { author: 'Eklavya P.', quote: 'Sebum build-up kam feel hota — scalp breathable.', rating: 5 },
    { author: 'Tanisha Q.', quote: 'Noise low, TV ke time pe use kar leti hoon.', rating: 5 },
    { author: 'Udit M.', quote: 'Battery indicator helpful hai — time pe charge.', rating: 4 },
    { author: 'Jaya K.', quote: 'Sensitive scalp pe bhi irritation nahi.', rating: 5 },
    { author: 'Irfan H.', quote: 'Buttons simple — family sab use kar lete.', rating: 4 },
    { author: 'Garima L.', quote: 'Dry scalp itching me kaafi aaram.', rating: 5 },
    { author: 'Vivek G.', quote: 'Office se aane ke baad neck tightness gayab.', rating: 5 },
    { author: 'Nikita S.', quote: 'Oil massage ke saath combo best lagta hai.', rating: 5 },
    { author: 'Omkar T.', quote: 'Charge fast, 2-3 din chal jaata hai.', rating: 4 },
    { author: 'Bhawna R.', quote: 'Grip non-slip — wet hands me bhi theek.', rating: 5 },
    { author: 'Suman P.', quote: 'Hair roots strong feel hote — breakage kam.', rating: 5 },
    { author: 'Lakshay D.', quote: 'Lightweight — hand fatigue nahi hoti.', rating: 4 },
    { author: 'Ruchi N.', quote: 'Temples pe circular motion — instant calm.', rating: 5 },
    { author: 'Yashika V.', quote: 'Shower me use karna easy — water resistant.', rating: 5 },
    { author: 'Hriday K.', quote: 'Charge once, 5-6 sessions easily ho jate.', rating: 4 },
    { author: 'Sejal M.', quote: 'Hair volume thoda improve feel hua.', rating: 5 },
    { author: 'Paras J.', quote: 'Travel me bhi essential ban gaya.', rating: 4 },
    { author: 'Tara P.', quote: 'Gift diya — sabko pasand aaya.', rating: 5 },
    { author: 'Zain I.', quote: 'Scalp pe gentle, par effective.', rating: 5 },
    { author: 'Naman O.', quote: 'Timer auto-off — overuse nahi hota.', rating: 4 },
    { author: 'Ayesha C.', quote: 'Design sleek aur sturdy.', rating: 5 },
    { author: 'Kabya F.', quote: 'Charging port covered — safe.', rating: 4 },
    { author: 'Rida E.', quote: 'Post-work relaxation guaranteed.', rating: 5 },
    { author: 'Manav S.', quote: 'Budget me best scalp massager.', rating: 5 },
    { author: 'Ila T.', quote: 'Hair oiling se pehle 2 min — absorption boost.', rating: 4 },
    { author: 'Devanshi Q.', quote: 'Headache me calm feel hota — 7/10 relief.', rating: 5 }
  ]
};

// Reviews: Electric Heating Pad
export const reviewsHeatingPad: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Nisha K.', quote: 'Period cramps me 10–15 min use se garam comfort milta hai. Fabric soft hai.', rating: 5 },
    { author: 'Rahul S.', quote: 'Lower back pain ke liye daily sham ko lagata hoon. Heat jaldi aa jati hai.', rating: 5 },
    { author: 'Pritam', quote: 'Auto cut‑off safety accha laga. Pouch size perfect aur leak proof.', rating: 4 },
    { author: 'Mona D.', quote: 'Office se aane ke baad neck pe rakh leti hoon. Relax feel hota hai.', rating: 5 },
    { author: 'Jagdish V.', quote: 'Heating level medium par bhi kaafi hot. Value for money.', rating: 4 },
    { author: 'Snehal P.', quote: 'Period cramps me warm relief — 10 min me sukoon.', rating: 5 },
    { author: 'Ishan R.', quote: 'Back spasm ke time pe kaafi madad karta hai.', rating: 4 },
    { author: 'Payal S.', quote: 'Fabric soft, skin pe gentle — rash nahi hota.', rating: 5 },
    { author: 'Zeeshan K.', quote: 'Heat evenly spread hoti — koi hot spot nahi.', rating: 5 },
    { author: 'Garv M.', quote: 'Charging/plug-in easy, cord length theek.', rating: 4 },
    { author: 'Ritika J.', quote: 'Office chair me lumbar area pe daily lagati hoon.', rating: 5 },
    { author: 'Usha D.', quote: 'Knee pain me bhi soothing garamahat milti hai.', rating: 5 },
    { author: 'Harsh V.', quote: 'Muscle strain me recovery fast feel hoti.', rating: 4 },
    { author: 'Kanika L.', quote: 'Leak-proof pouch — tension free heating.', rating: 5 },
    { author: 'Dhruv T.', quote: 'Auto shut-off safety kaafi useful hai.', rating: 4 },
    { author: 'Meena R.', quote: 'Neck stiffness me 15 min — relief.', rating: 5 },
    { author: 'Anil P.', quote: 'Fabric cover washable — maintain karna easy.', rating: 4 },
    { author: 'Jaya S.', quote: 'Lower abdomen cramps me perfect comforting heat.', rating: 5 },
    { author: 'Varun B.', quote: 'Back support ke saath use kiya — acha lagta hai.', rating: 5 },
    { author: 'Naina T.', quote: 'Lightweight, carry karna simple.', rating: 4 },
    { author: 'Kritika H.', quote: 'Warmth gentle par effective — 7/10 pain relief.', rating: 5 },
    { author: 'Om D.', quote: 'Switches intuitive — mode change easy.', rating: 4 },
    { author: 'Pooja V.', quote: 'Period me saviour — roz 10 min.', rating: 5 },
    { author: 'Raman K.', quote: 'Heat jaldi build hoti — wait nahi karna padta.', rating: 4 },
    { author: 'Esha P.', quote: 'Shoulder knots me bhi kaam karta.', rating: 5 },
    { author: 'Faizan M.', quote: 'Pouch size back aur tummy dono pe fit.', rating: 4 },
    { author: 'Gauri N.', quote: 'Cover soft — skin irritation zero.', rating: 5 },
    { author: 'Yogita C.', quote: 'Bedtime pe lagati hoon — relax milta hai.', rating: 5 },
    { author: 'Tarun R.', quote: 'Heat 2 min me ready — quick use.', rating: 4 },
    { author: 'Aakriti L.', quote: 'Travel pe bhi carry — lightweight.', rating: 5 },
    { author: 'Samar J.', quote: 'Old age knee pain me helpful.', rating: 5 },
    { author: 'Bhavna D.', quote: 'Period day 1 pe best — pain manageable.', rating: 5 },
    { author: 'Nakul I.', quote: 'Auto cut-off pe trust hai — safe feel.', rating: 4 },
    { author: 'Simar P.', quote: 'Neck pillow ke saath pair karke use karti.', rating: 5 },
    { author: 'Vikas H.', quote: 'Spine stiffness me warm comfort milta.', rating: 4 },
    { author: 'Ira K.', quote: 'Fabric sweat nahi karta — breathable.', rating: 5 },
    { author: 'Reyhan O.', quote: 'Timer accurate — overheat nahi hota.', rating: 4 },
    { author: 'Tina Q.', quote: 'Backache long day ke baad gayab.', rating: 5 },
    { author: 'Utkarsh E.', quote: 'Cord detachable — store karna easy.', rating: 4 },
    { author: 'Zara H.', quote: 'Gift diya — mom ko bahut pasand.', rating: 5 },
    { author: 'Manish G.', quote: 'Heat level low/medium sufficient.', rating: 4 },
    { author: 'Hiral S.', quote: 'Cramps me relief quick milta.', rating: 5 },
    { author: 'Ojas P.', quote: 'Lower back pe perfect fit.', rating: 5 },
    { author: 'Nisha V.', quote: 'Warmth steady rehti — no fluctuation.', rating: 5 },
    { author: 'Prashant U.', quote: 'Budget friendly and effective.', rating: 4 },
    { author: 'Kajal D.', quote: 'Long wire — extension ki zarurat nahi.', rating: 5 },
    { author: 'Yuvika A.', quote: 'Daily routine me add kar liya.', rating: 5 }
  ]
};

// Reviews: Kitchen Weighing Scale
export const reviewsScale: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Priti', quote: 'Baking ke liye accurate readings. Tare function daily use hota hai.', rating: 5 },
    { author: 'Gaurav', quote: 'Display clear hai, buttons simple. Price ke hisab se solid.', rating: 5 },
    { author: 'Amisha', quote: 'Weight loss diet me portion control ke liye helpful.', rating: 4 },
    { author: 'Sumit', quote: 'Lightweight aur compact, slab pe easily fit ho jata.', rating: 4 },
    { author: 'Nirmal', quote: 'Units switch karna easy — g/oz/lb. Battery backup theek.', rating: 5 },
    { author: 'Rupal D.', quote: 'Meal prep me tare function life saver.', rating: 5 },
    { author: 'Aditya S.', quote: '1 g precision baking me perfect measurements.', rating: 4 },
    { author: 'Meera L.', quote: 'Display bright, kitchen lights me clearly dikhta.', rating: 5 },
    { author: 'Faiz M.', quote: 'Auto-off useful — battery bachti hai.', rating: 4 },
    { author: 'Kanav J.', quote: 'Platform stable — spill hone par bhi theek raha.', rating: 5 },
    { author: 'Esha P.', quote: 'Diet tracking me grams accurate — macros easy.', rating: 5 },
    { author: 'Varsha K.', quote: 'Buttons responsive, koi delay nahi.', rating: 4 },
    { author: 'Hardik R.', quote: '10 kg capacity — batch cooking ke liye badiya.', rating: 5 },
    { author: 'Naina Q.', quote: 'Slim design, drawer me easily fit.', rating: 5 },
    { author: 'Om T.', quote: 'Unit switch quick — g se oz instant.', rating: 4 },
    { author: 'Sakshi V.', quote: 'Cleaning easy — wet cloth se saaf.', rating: 5 },
    { author: 'Yash G.', quote: 'Starter ke liye perfect scale — simple and accurate.', rating: 5 },
    { author: 'Irfan U.', quote: 'Overload indicator helpful laga.', rating: 4 },
    { author: 'Kriti P.', quote: 'Bowl tare feature daily kaam aata.', rating: 5 },
    { author: 'Paresh D.', quote: 'Rubber feet — countertop pe slip nahi karta.', rating: 4 },
    { author: 'Ria S.', quote: 'Biscuit recipes me consistent results.', rating: 5 },
    { author: 'Tushar H.', quote: 'Battery life achhi — mahine bhar chal gaya.', rating: 4 },
    { author: 'Jasmin A.', quote: 'Readout fast, lag nahi hai.', rating: 5 },
    { author: 'Deven C.', quote: 'Yeast proofing ke liye accurate water weight.', rating: 4 },
    { author: 'Priyanka L.', quote: 'Coffee beans measure karne me bhi great.', rating: 5 },
    { author: 'Gagan B.', quote: 'Calibration default me hi sahi tha.', rating: 4 },
    { author: 'Shreya M.', quote: 'Recipe follow karna ab easy lagta.', rating: 5 },
    { author: 'Vikrant N.', quote: 'Compact + sturdy — long lasting lagta.', rating: 5 },
    { author: 'Anvi D.', quote: 'Letters clear, backlight helpful.', rating: 5 },
    { author: 'Kunal P.', quote: 'Bulk dals aur flour weigh karna easy.', rating: 4 },
    { author: 'Roshni V.', quote: 'Design minimal, countertop pe achha lagta.', rating: 5 },
    { author: 'Abhinav S.', quote: 'Responsive tare — zero immediately.', rating: 5 },
    { author: 'Heena O.', quote: 'Package safely aaya, scratch free.', rating: 4 },
    { author: 'Mohit K.', quote: 'Diet portioning me acha control mila.', rating: 5 },
    { author: 'Palak R.', quote: 'Backlight low light me helpful.', rating: 5 },
    { author: 'Zain A.', quote: 'Cereal bowl tare karke milk add kar leta.', rating: 4 },
    { author: 'Jatin Y.', quote: 'Scale stable — motion me bhi reading steady.', rating: 4 },
    { author: 'Nupur T.', quote: 'Small footprint, storage friendly.', rating: 5 },
    { author: 'Saurav E.', quote: 'Liquid oz measurement bhi accurate.', rating: 4 },
    { author: 'Isha N.', quote: 'Batter consistency maintain karna easy.', rating: 5 },
    { author: 'Kartik D.', quote: 'Great for soap making experiments too!', rating: 5 },
    { author: 'Tanmay P.', quote: 'Manual clear, setup one minute.', rating: 4 },
    { author: 'Yuvika S.', quote: 'Macros track karne walon ke liye must.', rating: 5 },
    { author: 'Nakul B.', quote: 'Affordable aur accurate.', rating: 5 },
    { author: 'Simran C.', quote: 'Bread dough hydration ab exact.', rating: 5 },
    { author: 'Vani M.', quote: 'Heat resistant platform — chai steam se koi issue nahi.', rating: 4 },
    { author: 'Oviya H.', quote: 'Auto-off time sahi tuned.', rating: 4 },
    { author: 'Raghav P.', quote: 'Weighing halwa mix — mess free.', rating: 5 },
    { author: 'Aanya E.', quote: 'Design stylish — kitchen aesthetics me fit.', rating: 5 },
    { author: 'Ila G.', quote: 'Pan rakho, tare press karo — perfect zero.', rating: 5 },
    { author: 'Dev H.', quote: 'Warranty aur packaging dono ache the.', rating: 4 }
  ]
};

// Reviews: Mini Butterfly Massager (same scale as Mimo)
export const reviewsButterfly: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Sonia', quote: 'Neck pe 10 min lagaya, stiffness kam ho gayi. Gel pads soft hain.', rating: 5 },
    { author: 'Harsh', quote: 'Gym ke baad recovery ke liye badiya. USB se charge ho jata hai.', rating: 5 },
    { author: 'Reena', quote: 'Compact aur carry karne me easy. Noise bhi bahut kam.', rating: 4 },
    { author: 'Mudit', quote: 'Modes useful hain—warm up aur relax dono try kiya.', rating: 4 },
    { author: 'Payal', quote: 'Skin friendly pads, irritation nahi hua. Price worth hai.', rating: 5 },
    { author: 'Rohit', quote: 'Sticking easy — gel pads skin pe comfortable.', rating: 5 },
    { author: 'Palak', quote: 'Mode 2 recovery ke liye perfect lagta hai.', rating: 4 },
    { author: 'Ishan', quote: 'USB rechargeable — power bank se bhi chala liya.', rating: 5 },
    { author: 'Zara', quote: 'Shoulder knots me soothing pulses feel hote.', rating: 5 },
    { author: 'Gautam', quote: 'Noise low — TV dekhte hue bhi use.', rating: 4 },
    { author: 'Aisha', quote: 'Back aur arms dono pe kaam karta — portable.', rating: 5 },
    { author: 'Kabir', quote: 'Buttons simple — one press operation.', rating: 4 },
    { author: 'Nidhi', quote: 'Gym ke baad DOMS me relief mila.', rating: 5 },
    { author: 'Farhan', quote: 'Pad size neck aur shoulder dono pe fit.', rating: 4 },
    { author: 'Meera', quote: 'Travel friendly — pouch me carry kar leti.', rating: 5 },
    { author: 'Tanya', quote: 'Sticky pads reusable — value for money.', rating: 5 },
    { author: 'Yash', quote: 'Intensity adjustable — gentle se strong.', rating: 4 },
    { author: 'Anushka', quote: 'Skin irritation bilkul nahi — sensitive skin friendly.', rating: 5 },
    { author: 'Dev', quote: 'Warm-up mode try kiya — achha lagta.', rating: 4 },
    { author: 'Riya', quote: 'Office me 10 min break pe laga leti.', rating: 5 },
    { author: 'Hemant', quote: 'Charging fast — 3-4 sessions ho jate.', rating: 4 },
    { author: 'Ira', quote: 'Low noise discreet operation.', rating: 5 },
    { author: 'Jay', quote: 'Back seat me bhi laga liya — portable.', rating: 5 },
    { author: 'Kajal', quote: 'Modes variety sahi — recovery aur relax.', rating: 5 },
    { author: 'Lakshay', quote: 'Pads stickiness long lasting.', rating: 4 },
    { author: 'Mansi', quote: 'Arms soreness me quick aaram.', rating: 5 },
    { author: 'Naman', quote: 'Recharge ek baar ki to 4 sessions.', rating: 4 },
    { author: 'Ojas', quote: 'Carry case handy lagta.', rating: 5 },
    { author: 'Prachi', quote: 'Under clothes discreetly lag jata.', rating: 5 },
    { author: 'Rachit', quote: 'Timer useful — overuse nahi hota.', rating: 4 },
    { author: 'Sana', quote: 'Warm sensation relaxing lagti.', rating: 5 },
    { author: 'Tanvi', quote: 'Neck se shoulder tak ache se cover.', rating: 5 },
    { author: 'Utkarsh', quote: 'Gel pads replaceable — maintenance easy.', rating: 4 },
    { author: 'Vani', quote: 'Workout ke baad cool-down jaisa feel.', rating: 5 },
    { author: 'Wasim', quote: 'Stiffness me daily 10 min beneficial.', rating: 5 },
    { author: 'Zainab', quote: 'Compact design — desk drawer me fit.', rating: 5 },
    { author: 'Aqsa', quote: 'Charging indicator helpful lagta.', rating: 4 },
    { author: 'Fiza', quote: 'Skin pe gentle tap pulses — soothing.', rating: 5 },
    { author: 'Yasir', quote: 'Value for price — gifting ke liye bhi nice.', rating: 5 },
    { author: 'Arham', quote: 'Back of neck pe best result mila.', rating: 5 },
    { author: 'Nida', quote: 'Pads cleaning easy — wipe se ho jata.', rating: 4 },
    { author: 'Harpreet', quote: 'Under-collar lagake kaam bhi kar liya.', rating: 5 },
    { author: 'Gurpreet', quote: 'Intensity 3 pe sabse soothing.', rating: 5 },
    { author: 'Simran', quote: 'Portable aur user-friendly.', rating: 5 },
    { author: 'Jaspreet', quote: 'Modes transition smooth.', rating: 4 },
    { author: 'Amrit', quote: 'Battery backup achha hai.', rating: 5 },
    { author: 'Navjot', quote: 'Sticky pads after 2 weeks bhi theek.', rating: 4 },
    { author: 'Manpreet', quote: 'Stressful days me must-have.', rating: 5 },
    { author: 'Ravneet', quote: 'Charging port sturdy — koi wobble nahi.', rating: 4 },
    { author: 'Parminder', quote: 'Compact + effective — recommend.', rating: 5 },
    { author: 'Kamal', quote: 'Neck cramps me 8/10 relief.', rating: 5 }
  ]
};


// Reviews: Posture Corrector
export const reviewsPosture: ReviewsSummary = {
  ratingAvg: 5,
  ratingCount: 50,
  testimonials: [
    { author: 'Ankit M.', quote: 'WFH me lambi sitting se neck pain hota tha—yeh brace ne posture sudhara aur dard kam ho gaya.', rating: 5 },
    { author: 'Priya S.', quote: 'Lightweight aur under t‑shirt dikhta bhi nahi. 2 hafte me kaafi farq mehsoos hua.', rating: 5 },
    { author: 'Rohit G.', quote: 'Gym ke baad shoulders tight rehte the, ab alignment better lagta hai.', rating: 4 },
    { author: 'Shivani K.', quote: 'Office me daily 30 min pehenti hu. Slouching habit break ho rahi hai.', rating: 5 },
    { author: 'Deepak V.', quote: 'Straps breathable hain, garmi me bhi theek lagta hai.', rating: 4 },
    { author: 'Rakesh P.', quote: 'Shoulders seedhe rehne lage, pain reduce.', rating: 5 },
    { author: 'Sneha T.', quote: 'Zoom calls pe bhi discreet — slim design.', rating: 5 },
    { author: 'Gagan S.', quote: 'Gym warm-up me posture set ho jata.', rating: 4 },
    { author: 'Isha K.', quote: 'Underarm me chafing nahi — edges soft.', rating: 5 },
    { author: 'Kabir Y.', quote: '2 weeks me slouching habit kaafi kam.', rating: 4 },
    { author: 'Ananya D.', quote: 'Study sessions me back support acha.', rating: 5 },
    { author: 'Vikram H.', quote: 'Straps adjustable — fit customize ho jata.', rating: 4 },
    { author: 'Pooja M.', quote: 'WFH long hours — fatigue kam lagti.', rating: 5 },
    { author: 'Rohini L.', quote: 'Shirt ke niche bilkul noticeable nahi.', rating: 5 },
    { author: 'Tarun S.', quote: 'Back alignment better — stretch ke saath use.', rating: 4 },
    { author: 'Nidhi A.', quote: 'Breathable material — garmi me bhi comfortable.', rating: 5 },
    { author: 'Ojas R.', quote: 'Velcro strong — slip nahi hota.', rating: 4 },
    { author: 'Palak E.', quote: 'Sitting posture improve — dard kam.', rating: 5 },
    { author: 'Rehan J.', quote: 'Build solid — daily use me durable.', rating: 4 },
    { author: 'Tanvi Q.', quote: 'Routine me 30 min add kiya — habit ban gayi.', rating: 5 },
    { author: 'Utkarsh L.', quote: 'Back pain noticeably reduce 10 din me.', rating: 5 },
    { author: 'Yash V.', quote: 'Under clothes line show nahi hoti.', rating: 4 },
    { author: 'Aisha N.', quote: 'Shoulder rounding control me aaya.', rating: 5 },
    { author: 'Dev P.', quote: 'Instructions clear — pehnna asaan.', rating: 5 },
    { author: 'Farhan O.', quote: 'Bike ride pe bhi posture sahi rakha.', rating: 4 },
    { author: 'Garima C.', quote: 'Office desk setup ke saath best.', rating: 5 },
    { author: 'Harshit Z.', quote: 'Stretch bands ke saath combo helpful.', rating: 5 },
    { author: 'Ira D.', quote: 'Collarbone pressure nahi — cushiony straps.', rating: 4 },
    { author: 'Jatin W.', quote: 'Back ko reminder jaisa — bend karte hi yaad aata.', rating: 5 },
    { author: 'Kritika R.', quote: 'Neck strain me bhi farq aaya.', rating: 5 },
    { author: 'Lakshay M.', quote: 'Daily 20-30 min — muscle memory ban rahi.', rating: 5 },
    { author: 'Mansi O.', quote: 'Travel me carry — lightweight.', rating: 5 },
    { author: 'Nakul F.', quote: 'Velcro quality acchi — loose nahi hota.', rating: 4 },
    { author: 'Om V.', quote: 'Corrector slim — hoodie ke niche invisible.', rating: 5 },
    { author: 'Prisha B.', quote: 'After-surgery posture support me helpful.', rating: 4 },
    { author: 'Ritesh T.', quote: 'Long coding sessions — back fresh lagta.', rating: 5 },
    { author: 'Sana G.', quote: 'Size chart accurate — fit perfect aaya.', rating: 5 },
    { author: 'Tushar D.', quote: 'Neck hunch gradually reduce.', rating: 4 },
    { author: 'Vani H.', quote: 'No skin irritation — breathable mesh.', rating: 5 },
    { author: 'Zoya F.', quote: 'Workday ke end me fatigue kam.', rating: 5 },
    { author: 'Aarav E.', quote: 'Back cracking habit chuti — posture mindful.', rating: 4 },
    { author: 'Bhavya L.', quote: 'Shoulder alignment visible better.', rating: 5 },
    { author: 'Charu N.', quote: 'Gym ke baad cooldown me pehen leti.', rating: 5 },
    { author: 'Dhruv Q.', quote: 'Underarm discomfort nahi — edges soft.', rating: 5 },
    { author: 'Ekta K.', quote: 'Straps ko set karna easy — 1 min.', rating: 4 },
    { author: 'Falak M.', quote: 'Office commute me bhi comfortable.', rating: 5 },
    { author: 'Girish A.', quote: 'Initial 10 min thoda awkward, phir perfect.', rating: 4 },
    { author: 'Hansika U.', quote: 'Daily reminder jaisa — slouch mat karo.', rating: 5 },
    { author: 'Ipsita C.', quote: 'Confidence boost — straight walk.', rating: 5 }
  ]
};

// Backwards-compat default export used across components
export const reviews: ReviewsSummary = reviewsButterfly;

// Reviews by slug
export const reviewsBySlug: Record<string, ReviewsSummary> = {
  'head-massager': reviewsHead,
  'posture-corrector': reviewsPosture,
  'foot-massager': reviewsFoot,
  'electric-heating-pad': reviewsHeatingPad,
  'mimo-mini-massager': reviewsMimo,
  'mini-butterfly-massager': reviewsButterfly,
  'kitchen-weighing-scale': reviewsScale,
};



// Names and cities for live sales popup
export const liveNames: string[] = [
  'Aarav','Vivaan','Aditya','Vihaan','Arjun','Reyansh','Muhammad','Sai','Ayaan','Krishna',
  'Ishaan','Rudra','Kabir','Rohan','Dhruv','Atharv','Arnav','Param','Yuvraj','Harshit',
  'Ananya','Aarohi','Diya','Myra','Meera','Anika','Sara','Kiara','Aadhya','Saanvi',
  'Lavanya','Ira','Navya','Aanya','Advika','Ishita','Trisha','Niharika','Ria','Prisha',
  'Karan','Manish','Ritesh','Sagar','Rahul','Ravi','Sunil','Vikas','Sandeep','Amit',
  'Pooja','Neha','Ritika','Shreya','Muskan','Prerna','Kritika','Roshni','Payal','Sneha',
  'Zoya','Farhan','Imran','Faizan','Aqsa','Ayesha','Yasir','Fiza','Arham','Nida',
  'Harpreet','Gurpreet','Simran','Jaspreet','Amrit','Navjot','Manpreet','Ravneet','Parminder','Kamal',
  'Shivam','Akash','Ankita','Bhavesh','Chirag','Deepak','Esha','Gauri','Hemant','Isha',
  'Jay','Kajal','Lakshay','Madhav','Nisha','Ojas','Prachi','Rachit','Sana','Tanvi',
  'Yash','Rhea','Tanya','Pratik','Anushka','Dev','Tarun','Naman','Ibrahim','Rehan',
  'Kabya','Aishwarya','Mitali','Sujoy','Pallavi','Hrithik','Siddharth','Irfan','Sameer','Anubhav',
  'Bhumi','Mehak','Dhriti','Vedant','Harsh','Hardik','Jatin','Keshav','Om','Parth',
  'Ritvik','Anmol','Tushar','Utkarsh','Yogesh','Zubair','Zainab','Wasim','Tanay','Pranjal',
  'Sourav','Rupali','Mehul','Kinjal','Hetal','Devanshi','Palak','Naman','Vibhor','Jahnvi',
  'Aman','Harsha','Charu','Chaitanya','Divyansh','Ekta','Falak','Girish','Hansika','Ipsita'
]

export const liveCities: string[] = [
  'Patiala','Palampur','Palampur','Ludhiana','Amritsar','Jalandhar','Bathinda','Moga','Mohali','Chandigarh',
  'Delhi','Gurugram','Noida','Faridabad','Ghaziabad','Jaipur','Jodhpur','Udaipur','Kota','Ajmer',
  'Mumbai','Thane','Pune','Nagpur','Nashik','Aurangabad','Indore','Bhopal','Gwalior','Raipur',
  'Lucknow','Kanpur','Varanasi','Prayagraj','Agra','Meerut','Bareilly','Gorakhpur','Aligarh','Moradabad',
  'Kolkata','Howrah','Asansol','Siliguri','Durgapur','Patna','Gaya','Muzaffarpur','Ranchi','Jamshedpur',
  'Hyderabad','Warangal','Nizamabad','Vijayawada','Visakhapatnam','Guntur','Tirupati','Bengaluru','Mysuru','Mangaluru',
  'Chennai','Coimbatore','Madurai','Trichy','Salem','Erode','Kochi','Thiruvananthapuram','Kozhikode','Kollam',
  'Surat','Ahmedabad','Rajkot','Bhavnagar','Jamnagar','Vadodara','Porbandar','Morbi','Junagadh','Gandhinagar',
  'Dehradun','Haridwar','Rishikesh','Haldwani','Shimla','Solan','Hamirpur','Una','Kangra','Dharamshala',
  'Srinagar','Jammu','Leh','Udhampur','Imphal','Aizawl','Shillong','Gangtok','Itanagar','Kohima',
  'Bilaspur','Rewa','Satna','Guna','Hoshangabad','Ratlam','Dewas','Ujjain','Mandya','Belagavi',
  'Hubballi','Davanagere','Ballari','Tumakuru','Hassan','Hampi','Rohtak','Hisar','Panipat','Sonipat',
  'Karnal','Panchkula','Ambala','Sirsa','Yamunanagar','Rewari','Fatehabad','Bhiwani','Palwal','Kurukshetra'
]
